// Port of the helpers xivModdingFramework's SqPack readers call (TexTools commit 25b3ae72):
// SqPack/FileTypes/Dat.cs Pad(int, int, bool), Write3IntBuffer, Read3IntBuffer(BinaryReader, bool),
// BeginReadCompressedBlocks, CompleteReadCompressedBlocks; Helpers/IOUtil.cs Decompressor.
using System.IO.Compression;

namespace DawntrailReady.Core.SqPack;

public static partial class Dat
{
    /// <summary>Pads a given int length to the next padding interval.</summary>
    public static int Pad(int size, int paddingTarget, bool forcePadding = false)
    {
        var pad = paddingTarget - (size % paddingTarget);
        if (pad == paddingTarget && !forcePadding)
        {
            return size;
        }
        return size + pad;
    }

    public static void Write3IntBuffer(List<byte> bufferTarget, uint[] dataToAdd)
    {
        bufferTarget.AddRange(BitConverter.GetBytes(dataToAdd[0]));
        bufferTarget.AddRange(BitConverter.GetBytes(dataToAdd[1]));
        bufferTarget.AddRange(BitConverter.GetBytes(dataToAdd[2]));
    }

    public static uint[] Read3IntBuffer(BinaryReader br, bool shortOnly = false)
    {
        uint[] data = new uint[3];
        if (shortOnly)
        {
            data[0] = br.ReadUInt16();
            data[1] = br.ReadUInt16();
            data[2] = br.ReadUInt16();
        }
        else
        {
            data[0] = br.ReadUInt32();
            data[1] = br.ReadUInt32();
            data[2] = br.ReadUInt32();
        }
        return data;
    }

    /// <summary>
    /// Reads a sequence of blocks from the stream now; each returned function yields one block's uncompressed bytes
    /// when CompleteReadCompressedBlocks runs it (TexTools returns Task.Run inflation tasks here).
    /// </summary>
    public static List<Func<byte[]>> BeginReadCompressedBlocks(BinaryReader br, int blockCount, long offset = -1, bool lastInFile = false)
    {
        if (blockCount == 0)
        {
            return new();
        }

        if (offset > 0)
        {
            br.BaseStream.Seek(offset, SeekOrigin.Begin);
        }

        var tasks = new List<Func<byte[]>>();

        for (int i = 0; i < blockCount; i++)
        {
            byte[] data;

            var start = br.BaseStream.Position;

            // Some variety of magic numbers presumably?
            var sixTeen = br.ReadByte();

            // TexTools: a catch for old improperly spaced blocks generated by Endwalker and earlier TexTools.
            while (sixTeen != 16 && sixTeen == 0)
            {
                sixTeen = br.ReadByte();
            }
            var zeros = br.ReadBytes(3);

            var zero = br.ReadInt32();

            if (sixTeen != 16 || zero != 0 || zeros.Any(x => x != 0))
            {
                throw new Exception("Unable to locate valid compressed block header.");
            }

            // Relevant info.
            var partCompSize = br.ReadInt32();
            var partDecompSize = br.ReadInt32();

            Func<byte[]> task;

            void readBlockPadding()
            {
                var end = br.BaseStream.Position;
                var length = end - start;
                var targetLength = Pad((int)length, 128);
                var remaining = targetLength - length;

                var paddingData = br.ReadBytes((int)remaining);

                var sixTeenIndex = Array.IndexOf(paddingData, (byte)16);

                // An old broken TexTools import that has improper block spacing.
                // Rewind the stream to the start of the next block.
                if (sixTeenIndex != -1)
                {
                    var rewind = paddingData.Length - sixTeenIndex;
                    br.BaseStream.Position = br.BaseStream.Position - rewind;
                }
                else if (paddingData.Any(x => x != 0))
                {
                    if (lastInFile && i != blockCount - 1)
                    {
                        throw new Exception("Unexpected real data in compressed data block padding section.");
                    }
                }
            }

            if (partCompSize == 32000)
            {
                data = br.ReadBytes(partDecompSize);
                readBlockPadding();
                var stored = data;
                task = () => stored;
            }
            else
            {
                data = br.ReadBytes(partCompSize);
                readBlockPadding();

                var compressed = data;
                task = () => Decompressor(compressed, partDecompSize);
            }

            tasks.Add(task);
        }

        return tasks;
    }

    /// <summary>
    /// Runs every function from BeginReadCompressedBlocks in order and writes the results sequentially into
    /// destBuffer (growing it when needed). Returns the number of bytes written and the possibly new buffer.
    /// </summary>
    public static (int BytesWritten, byte[] Buffer) CompleteReadCompressedBlocks(List<Func<byte[]>> tasks, byte[] destBuffer, int destOffset)
    {
        int currentOffset = destOffset;
        foreach (var task in tasks)
        {
            var result = task();

            if (currentOffset + result.Length >= destBuffer.Length)
            {
                var newSize = currentOffset + result.Length;
                var newArray = new byte[newSize];
                Array.Copy(destBuffer, 0, newArray, 0, destBuffer.Length);
                destBuffer = newArray;
            }
            result.CopyTo(destBuffer, currentOffset);
            currentOffset += result.Length;
        }
        var written = currentOffset - destOffset;
        return (written, destBuffer);
    }

    /// <summary>
    /// TexTools' IOUtil.Decompressor: raw-deflate inflate into a buffer of exactly uncompressedSize bytes
    /// (zero-filled if the stream ends early).
    /// </summary>
    public static byte[] Decompressor(byte[] compressedBytes, int uncompressedSize)
    {
        var decompressedBytes = new byte[uncompressedSize];

        using (var ms = new MemoryStream(compressedBytes))
        {
            using (var ds = new DeflateStream(ms, CompressionMode.Decompress, true))
            {
                int offset = 0; // offset for writing into buffer
                int bytesRead; // number of bytes read from Read operation
                while ((bytesRead = ds.Read(decompressedBytes, offset, uncompressedSize - offset)) > 0)
                {
                    offset += bytesRead;  // offset in buffer for results of next reading
                    if (bytesRead == uncompressedSize) break;
                }
            }
        }

        return decompressedBytes;
    }
}
